language: php
sudo: false
cache:
  directories:
  - $HOME/.composer/cache/files
matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_DEPLOYMENT=true
    - php: hhvm
    - php: nightly
    - php: 7.0
      env: COVERAGE=yes
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - if [[ $TRAVIS_REPO_SLUG = puli/cli ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script: if [[ $COVERAGE = yes ]]; then vendor/bin/phpunit --verbose --coverage-clover=coverage.clover; else vendor/bin/phpunit --verbose; fi

after_script: if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_success:
  - openssl aes-256-cbc -K $encrypted_7a05c4e35c71_key -iv $encrypted_7a05c4e35c71_iv
    -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && ($TRAVIS_BRANCH == 'master' || $TRAVIS_TAG != '') && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && ($TRAVIS_BRANCH == 'master' || $TRAVIS_TAG != '') && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && ($TRAVIS_BRANCH == 'master' || $TRAVIS_TAG != '') && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./puli.phar ; fi

notifications:
  webhooks:
    urls: ['https://webhooks.gitter.im/e/9ccc2378e6c0de6480f8']
    on_success: change
    on_failure: always
    on_start:   never

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: XufYEOR4sihf4gJ9zTizrupydaQnkCVZLDbdXRAmfVNgDQNkSI2a8aKyGxxH2YTmJn65DHiFAuNMv5LIwG1e1XuiuW4ZFsEOj7o+qV5NZCzkTiYY4qYVlsut2lk8Y6dOaJl9wjvBKxK/ELbs66M4NS/3qSluaGAL1K3DtuBzF0MFLT0S4HhwoYkkJaTx3XZcCNSJA7kxT/yhSpMOhlmVXw89yJbxHiVya/YVLBHGSFpN8WpHSYxZuOnWw4OZrvS/Le+v9cvxqK1JLzV6tKe6X3DtBRzyVoO+c0CXm7Q0nn+HYtuZHnn2uOsLb68kRo8R2jjRImF/q6xdhoUHmrKFa8GgaVZkYHoCYVIbX0e2DzLvgo5DXEs1H8sNKFBjI0zRj8B9CDV6Blqap3a4d6JBsmmTAt4sFENWU4Gekv/vfB9PEIjmbLl+5/YHQcHtzU+kMnAGzpJ2d+M9BOjiUPdEHSek7vaEdE5ySAMM/0PZo2y9ZP1Go7yzHybip3WdLO6G8Q0HOoYUL0orJ9rZOT+NYBIgWXHymyFM2TJvoGlgsQRzagVseyH8qbmGo1FuMrTGePYjCo00xT3S2RgW4nXMPi0Qx6dsTUqGZDr8v1Qz2gKJlgP/a7Wpd+P1km+ibkVyqb94CgCx3Ryxf7YBplUuPT9Th+f/AiGOFh9OLA729M4=
    file: puli.phar
    on:
      tags: true
